name: mails
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '50 1 * * 1-5'
jobs:
  mail:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install pip==23.0
          pip install --no-cache-dir -r requirements.txt
      - name: run scripts
        run: |
          python scripts/run-mail.py ${{ secrets.CONFIG_URL }} ${{ secrets.EMAIL }} ${{ secrets.EMAIL_PASS }}
